version: '2'
services:
    first-app:
        image: first
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://first-mysql:3306/first?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://first-elasticsearch:9200
        ports:
            - 8080:8080
    first-mysql:
        extends:
            file: mysql.yml
            service: first-mysql
    first-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: first-elasticsearch
