version: '2'
services:
    ngsvr-app:
        image: ngsvr
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://ngsvr-mariadb:3306/ngsvr
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ngsvr-mariadb:
        extends:
            file: mariadb.yml
            service: ngsvr-mariadb
